config/routes.rb
Rails.application.routes.draw do
  # get 'creatures/index'
  #
  # get 'creatures/fetch_race'
  #
  # get 'creatures/fetch_creature'
  #
  # get 'dice/roll'

  root 'main#index'
  
  get 'main/index'
  
  get 'login',       to: 'main#login'
  post 'login',      to: 'main#login'
  get 'logout',      to: 'main#logout'

  get  'signup',     to: 'main#signup'
  post 'signup',     to: 'main#signup'

  get 'admin',                to: 'admin#index'
  get 'admin/ironhedge',      to: 'admin#ironhedge',      as: 'ironhedge_edit'
  get 'admin/usergroup_edit', to: 'admin#usergroup_edit', as: 'usergroup_edit'

  post 'showlogin',  to: 'utility#showlogin'

  get   'utility/fetchUserList',    to: 'utility#fetcthUserList', as: 'userList'
  delete 'utility/removeUser/:id',  to: 'utility#removeUser',     as: 'removeUser'
  get   'utility/showEditUser/:id', to: 'utility#showEditUser',   as: 'showEditUser'
  patch 'utility/updateUser/:id',   to: 'utility#updateUser',     as: 'updateUser'

  post  'utility/addGroupToUser',        to: 'utility#addGroupToUser',      as: 'addGroupToUser'
  post  'utility/removeGroupFromUser',   to: 'utility#removeGroupFromUser', as: 'removeGroupFromUser'

  get   'utility/fetchGroupList',     to: 'utility#fetchGroupList',  as: "fetchGroupList"
  put  'utility/addNewGroup',         to: 'utility#addNewGroup',     as: 'addNewGroup'
  delete 'utility/removeGroup/:id',   to: 'utility#removeGroup',     as: 'removeGroup'

  get   'utility/fetchFighterAdminTable',    to: 'utility#fetchFighterAdminTable', as: 'fighterAdminTable'
  post  'utility/addFighterClass',           to: 'utility#addFighterClass' 
  patch 'utility/updateFighterClass/:id',    to: 'utility#updateFighterClass'
  get   'utility/editFighterClass/:id',      to: 'utility#editFighterClass'

  get   'utility/fetchThiefAdminTable', to: 'utility#fetchThiefAdminTable', as: 'thiefAdminTable'
  post  'utility/addThiefClass',        to: 'utility#addThiefClass' 
  patch 'utility/updateThiefClass/:id', to: 'utility#updateThiefClass'
  get   'utility/editThiefClass/:id',   to: 'utility#editThiefClass'

  get   'utility/fetchMagicianAdminTable', to: 'utility#fetchMagicianAdminTable', as: 'magicianAdminTable'
  get   'utility/editMagicianClass/:id',   to: 'utility#editMagicianClass'
  post  'utility/addMagicianClass',        to: 'utility#addMagicianClass'
  patch 'utility/updateMagicianClass/:id', to: 'utility#updateMagicianClass'

  get   'utility/fetchAlchemistAdminTable', to: 'utility#fetchAlchemistAdminTable', as: 'alchemistAdminTable'
  get   'utility/editAlchemistClass/:id',   to: 'utility#editAlchemistClass'
  post  'utility/addAlchemistClass',        to: 'utility#addAlchemistClass'
  patch 'utility/updateAlchemistClass/:id', to: 'utility#updateAlchemistClass'

  get   'utility/fetchPriestAdminTable', to: 'utility#fetchPriestAdminTable', as: 'priestAdminTable'
  get   'utility/editPriestClass/:id',   to: 'utility#editPriestClass'
  post  'utility/addPriestClass',        to: 'utility#addPriestClass'
  patch 'utility/updatePriestClass/:id', to: 'utility#updatePriestClass'
  
  delete 'utility/deleteIronClass'#,       to: 'utility#deleteIronClass'
  get    'utility/fetchSavingRollList'
  get    'utility/fetchSavingRollsAdminTable'

  get    'utility/fetchSavingRollInline/:srid', to: 'utility#srEditInline', as: 'srEditInline'
  post   'utility/srAdd', as: 'srAdd'
  delete 'utility/srDelete'
  
  ######################################################################################################3
  # dice api routes
  #################################
  
  get 'dice/fetchDiceBtns', to: 'dice#fetchDiceBtns'
  post 'dice/roll', to: 'dice#roll'

  ######################################################################################################3
  # jewel api routes
  #################################
  
  post 'jewel/cut', to: 'jewel#cut'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get 'index',               to: 'index'
    get 'fighterClassTable',   to: 'fighterClassTable'
  	get 'thiefClassTable',     to: 'thiefClassTable'
    get 'magicianClassTable',  to: 'magicianClassTable'
    get 'alchemistClassTable', to: 'alchemistClassTable'
    get 'priestClassTable',    to: 'priestClassTable'
  end
  
  ####################################
  # Creatures api
  ####################################
  get 'creatures/index',        to: 'creatures#index'
  get 'creatures/fetch_all',    to: 'creatures#fetch_all'
  get 'creatures/fetch_racelist'
  
  
  
 #match ':controller(/:action)(/:id)', via: [ :get,:post, :patch ] 
end

app/views/admin/_admin_sidebar_nav.html.erb
<!-- <div class="container-fluid"> -->
<nav class="navbar navbar-inverse sidebar" id="admin-nav" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h3 class="" href="#">Admin</h3>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li >
          <%= link_to usergroup_edit_path, remote: true, class: 'sidebar-nav-active greenshadow', onClick: 'toggleAdminSidebarSelected(this, "usergroup");', 'ng-click': "PanelCtrl['main'] = 'usergroup'".html_safe, target: "_self" do %>
            Users/Groups
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
          <% end %>
        </li>
        <li >
          <%= link_to "#", class: 'cyanshadow', onClick: 'toggleAdminSidebarSelected(this, "ironhedge");', 'ng-click': "PanelCtrl['main'] = 'ironhedge'".html_safe, target: "_self" do %>
            Ironhedge
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-fire"></span>
          <% end %>
          </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
</nav>
  <!-- </div> -->

<!-- admin.js contains javascript for the sidebar menu -->
<!-- <script type="text/javascript" src="admin.js">
</script> -->

app/views/admin/_alchemistAdminTable.html.erb
<div class="col-lg-12 tbl_ironhedgeclass" id="alchemist_admintable" ng-controller="ironAdminTableCtrl"> 

    <div class="col-lg-12 tableCaption-map"><h3>Alchemist Classes</h3></div>
    <div class="row borderBottom_redgrey">
        <div class="tblcol-rank tblhdr" style="left: 25px">Rank</div>
        <div class="tblhdr" style="left: 62px">EL</div>
        <div class="tblhdr" style="left:118px">AL</div>
        <div class="tblhdr epcolumn" style="left:137px">EP</div>
        <div class="tblhdr mpacolumn" style="left:180px">MI</div>
        <div class="tblhdr enccolumn" style="left:212px">ENC</div>
        <div class="tblhdr kpcolumn" style="left:253px">KP</div>
        <div class="tblhdr" style="left:297px">IP</div>
        <div class="tblhdr" style="left:331px">PW-1ST</div>
        <div class="tblhdr" style="left:370px">2ND</div>
        <div class="tblhdr" style="left:409px">3RD</div>
        <div class="tblhdr" style="left:448px">4TH</div>
        <div class="tblhdr tblhdr-actions" style="left:467px">Actions</div>
    </div>
    <div class="alchemist_row" id="alchemist_list">
        <% @aclasses.each do |ac| %>
            <%= render "admin/alchemist/classrow", ac: ac  %>
        <% end %>
    </div>
<div class="alchemist_row" id="addAlchemistData">
    <%= form_for @acnew, url: '/utility/addAlchemistClass', remote: true do |f| %>
    <div class="row">
        <div class="tbldata" style="left:  5px"><%= f.text_field :rank, size: 15 %></div>
        <div class="tbldata" style="left: 53px"><%= f.text_field :el, size: 2 %></div>
        <div class="tbldata" style="left: 86px"><%= f.text_field :al, size: 2 %></div>
        <div class="tbldata epcolumn" style="left: 93px"><%= f.text_field :ep, size: 5 %></div>
        <div class="tbldata mpacolumn" style="left:131px"><%= f.text_field :mi, size: 2 %></div>
        <div class="tbldata enccolumn" style="left:159px"><%= f.text_field :enc, size: 5 %></div>
        <div class="tbldata kpcolumn" style="left:200px"><%= f.text_field :kp, size: 2 %></div>
        <div class="tbldata" style="left:241px"><%= f.text_field :ip, size: 1 %></div>
        <div class="tbldata" style="left:290px"><%= f.text_field :q1, size: 1 %></div>
        <div class="tbldata" style="left:323px"><%= f.text_field :q2, size: 1 %></div>
        <div class="tbldata" style="left:355px"><%= f.text_field :q3, size: 1 %></div>
        <div class="tbldata" style="left:387px"><%= f.text_field :q4, size: 1 %></div>
        <div class="tbldata" style="left:410px"><%= f.submit "+" %></div>
    </div>
    <% end %>
    </div>
    <div class="clearleft">
        <button type="button" ng-click="backToTableIndex('alchemist')">Back</button> to Table Index
    </div>
</div>

app/views/admin/_fighterAdminTable.html.erb
<div class="col-lg-12 tbl_ironhedgeclass" id="fighter_admintable" ng-controller="ironAdminTableCtrl"> 
<!-- ng-show="ironPanelCtrl['adminTable'] == 'adminFighterTable'" -->
    <div class="col-lg-12 tableCaption"><h3>Fighter Classes</h3></div>
    <div class="row borderBottom_redgrey fighter_row">
        <div class="tblcol-rank tblhdr" style="left: 15px;">Rank</div>
        <div class="tblhdr" style="left: 10px;">EL</div>
        <div class="tblhdr" style="left: 75px;">AL</div>
        <div class="tblhdr epcolumn" style="left: 110px;">EP</div>
        <div class="tblhdr mpacolumn" style="left: 154px;">MS</div>
        <div class="tblhdr enccolumn" style="left: 200px;">ENC</div>
        <div class="tblhdr kpcolumn" style="left: 250px;">KP</div>
        <div class="tblhdr" style="left: 290px;">#AT</div>
        <div class="tblhdr tblhdr-actions" style="left: 320px;">Actions</div>
    </div>
    <div class="fighter_row" id="fighter_list">
        <% @fclasses.each do |fc| %>
            <%= render "admin/fighter/classrow", fc: fc  %>
        <% end %>
    </div>
    <div class="col-lg-12 fighter_row" id="addFigtherData">
        <%= form_for @fc, url: 'fighter/addClass', remote: true do |f| %>
            <div class="tbldata" style="left: -10px;"><%= f.text_field :rank, size: 20 %></div>
            <div class="tbldata" style="left: 3px;"><%= f.text_field :el, size: 2 %></div>
            <div class="tbldata" style="left: 41px;"><%= f.text_field :al, size: 2 %></div>
            <div class="tbldata" style="left: 59px;"><%= f.text_field :ep, size: 5 %></div>
            <div class="tbldata" style="left: 87px;"><%= f.text_field :ms, size: 2 %></div>
            <div class="tbldata" style="left: 117px;"><%= f.text_field :enc, size: 5 %></div>
            <div class="tbldata" style="left: 142px;"><%= f.text_field :kp, size: 2 %></div>
            <div class="tbldata" style="left: 168px;"><%= f.text_field :at, size: 1 %></div>
            <div class="tbldata" style="left: 191px;"><%= f.submit "+" %></div>
        <% end %>
    </div>
    <div class="clearleft">
        <button type="button" ng-click="backToTableIndex('fighter')">Back</button> to Table Index
    </div>
</div>

app/views/admin/_group.html.erb
<% @groups.each do |group| %>
  <div class="well well-sm">
    <li><%= group.name %></li>
  </div>
<% end -%>

app/views/admin/_grouplist.html.erb
<div id="groupListing">
  <%# @groups.each do |group| %>
    <div class="well well-sm" ng-repeat="group in grouplist track by group.id" id="wellforGroup{{group.id}}">
      <li>
        <div class="col-lg-11">
          {{group.name}}
        </div>
        <div class="col-lg-1">
          <button type="button" class="btn btn-sm groupDeleteBtn" ng-really-message="Confirm removal of Group:{{group.name}}" ng-really-click="removeGroup({{group.id}})">
            <span class="glyphicon glyphicon-remove"></span>
          </button>  
        </div>
      </li>
    </div>
  <%# end %>
</div>

app/views/admin/_hedgetables.html.erb
<div ng-controller="ironAdminTableCtrl">

    <h3>Ironhedge Admin Index of all tables</h3>
    <div class="col-lg-2">
        <table class="table table-stripped table-bordered">
            <caption>Character Classes</caption>
            <tbody>
                <tr>
                    <td class="text-center">
                        <button type="button" class="btn-getAdminClassTable" ng-click="getIronhedgeClassAdminTable('Fighter')">Fighter</button>
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        <button type="button" class="btn-getAdminClassTable" ng-click="getIronhedgeClassAdminTable('Thief')">Thief</button>
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        <button type="button" class="btn-getAdminClassTable" ng-click="getIronhedgeClassAdminTable('Magician')">Magician</button>
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        <button type="button" class="btn-getAdminClassTable" ng-click="getIronhedgeClassAdminTable('Alchemist')">Alchemist</button>
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        <button type="button" class="btn-getAdminClassTable" ng-click="getIronhedgeClassAdminTable('Priest')">Priest</button>
                    </td>
                </tr>
            </tbody>
        </table>

        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td class="text-center">
                        <button type="button" class="btn-getAdminClassTable" ng-click="getSavingRollsAdminTable();">Saving Rolls</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/_magicianAdminTable.html.erb
<div class="tbl_ironhedgeclass" id="magician_admintable" ng-controller="ironAdminTableCtrl"> 

    <div class="col-lg-12 tableCaption-map"><h3>Magician Classes</h3></div>
    <div class="row borderBottom_redgrey magician_row">
        <div class="tblcol-rank tblhdr" style="left: 25px">Rank</div>
        <div class="tblhdr" style="left:110px">EL</div>
        <div class="tblhdr" style="left:160px">AL</div>
        <div class="tblhdr epcolumn" style="left: 192px">EP</div>
        <div class="tblhdr mpacolumn" style="left: 222px">MI</div>
        <div class="tblhdr enccolumn" style="left: 258px">ENC</div>
        <div class="tblhdr kpcolumn" style="left: 296px">KP</div>
        <div class="tblhdr" style="left: 346px">DM</div>
        <div class="tblhdr" style="left: 369px">SW-1ST</div>
        <div class="tblhdr" style="left: 408px">2ND</div>
        <div class="tblhdr" style="left: 446px">3RD</div>
        <div class="tblhdr" style="left: 485px">4TH</div>
        <div class="tblhdr tblhdr-actions" style="left: 510px">Actions</div>
    </div>
    <div class="magician_row" id="magician_list">
        <% @mclasses.each do |mc| %>
            <%= render "admin/magician/classrow", mc: mc  %>
        <% end %>
    </div>
    <div class="magician_row" id="addMagicianData">
        <%= form_for @mcnew, url: '/utility/addMagicianClass', remote: true do |f| %>
        <div class="row">
            <div class="tbldata" style="left: 25px;"><%= f.text_field :rank, size: 20 %></div>
            <div class="tbldata" style="left: 64px;"><%= f.text_field :el, size: 2 %></div>
            <div class="tbldata" style="left: 87px;"><%= f.text_field :al, size: 2 %></div>
            <div class="tbldata epcolumn" style="left: 106px;"><%= f.text_field :ep, size: 5 %></div>
            <div class="tbldata mpacolumn" style="left: 135px;"><%= f.text_field :mi, size: 2 %></div>
            <div class="tbldata enccolumn" style="left: 164px;"><%= f.text_field :enc, size: 5 %></div>
            <div class="tbldata kpcolumn" style="left: 204px;"><%= f.text_field :kp, size: 2 %></div>
            <div class="tbldata" style="left: 256px;"><%= f.text_field :dm, size: 1 %></div>
            <div class="tbldata" style="left: 296px;"><%= f.text_field :q1, size: 1 %></div>
            <div class="tbldata" style="left: 327px;"><%= f.text_field :q2, size: 1 %></div>
            <div class="tbldata" style="left: 358px;"><%= f.text_field :q3, size: 1 %></div>
            <div class="tbldata" style="left: 390px;"><%= f.text_field :q4, size: 1 %></div>
            <div class="tbldata" style="left: 420px;"><%= f.submit "+" %></div>
        </div>
        <% end %>
    </div>
    <div class="clearleft">  
        <button type="button" ng-click="backToTableIndex('magician')">Back</button> to Table Index
    </div>
</div>

app/views/admin/_priestAdminTable.html.erb
<div class="tbl_ironhedgeclass" id="priest_admintable" ng-controller="ironAdminTableCtrl">  

    <div class="tableCaption-map"><h3>Priest Classes</h3></div>
    <div class="row borderBottom_redgrey priest_row">
        <div class="tblcol-rank tblhdr" style="left: 25px">Rank</div>
        <div class="tblhdr" style="left: 50px">EL</div>
        <div class="tblhdr" style="left: 90px">AL</div>
        <div class="tblhdr epcolumn" style="left: 105px">EP</div>
        <div class="tblhdr mpacolumn" style="left: 140px">MI</div>
        <div class="tblhdr enccolumn" style="left: 170px">ENC</div>
        <div class="tblhdr kpcolumn" style="left: 200px">KP</div>
        <div class="tblhdr" style="left: 230px">DI</div>
        <div class="tblhdr" style="left: 255px">PW-1ST</div>
        <div class="tblhdr" style="left: 285px">2ND</div>
        <div class="tblhdr" style="left: 325px">3RD</div>
        <div class="tblhdr" style="left: 364px">4TH</div>
        <div class="tblhdr tblhdr-actions" style="left: 415px">Actions</div>
    </div>
    <div class="priest_row" id="priest_list">
        <% @pclasses.each do |pc| %>
            <%= render "admin/priest/classrow", pc: pc  %>
        <% end %>
    </div>
    <div class="priest_row" id="addPriestData">
        <%= form_for @pcnew, url: '/utility/addPriestClass', remote: true do |f| %>
            <div class="row">
                <div class="tbldata" style="left: 20px"><%= f.text_field :rank, size: 15 %></div>
                <div class="tbldata" style="left: 40px"><%= f.text_field :el, size: 2 %></div>
                <div class="tbldata" style="left: 55px"><%= f.text_field :al, size: 2 %></div>
                <div class="tbldata epcolumn" style="left:  60px"><%= f.text_field :ep, size: 5 %></div>
                <div class="tbldata mpacolumn" style="left:  90px"><%= f.text_field :mi, size: 2 %></div>
                <div class="tbldata enccolumn" style="left: 112px"><%= f.text_field :enc, size: 5 %></div>
                <div class="tbldata kpcolumn" style="left: 148px"><%= f.text_field :kp, size: 2 %></div>
                <div class="tbldata" style="left: 175px"><%= f.text_field :di, size: 1 %></div>
                <div class="tbldata" style="left: 212px"><%= f.text_field :q1, size: 1 %></div>
                <div class="tbldata" style="left: 238px"><%= f.text_field :q2, size: 1 %></div>
                <div class="tbldata" style="left: 270px"><%= f.text_field :q3, size: 1 %></div>
                <div class="tbldata" style="left: 299px"><%= f.text_field :q4, size: 1 %></div>
                <div class="tbldata" style="left: 350px"><%= f.submit "+" %></div>
            </div>
        <% end %>
    </div>
    <div id="back-t">  
        <button type="button" ng-click="backToTableIndex('priest')">Back</button> to Table Index
    </div>
</div>

app/views/admin/_savingRollAdminTable.html.erb
<div class="col-lg-12 tbl_ironhedgesavingroll" id="savingroll_admintable" ng-controller="ironAdminTableCtrl"> 
  <div class="col-lg-4 savingRolls-table">
    <h2 class="savingRolls-tblHeader">Saving Rolls:</h2>
    <div class="savingRolls-Line2Div">
      <span class="savingRolls-Line2Left">Victim's:</span>
      <span class="savingRolls-Line2Right">EL</span>
    </div>
    <div class="savingRolls-Line3Div" id="">
      <span class="savingRolls-Line3Left">Str-Int</span>
      <span class="savingRolls-Line3Right" style="margin-left: 60px">1</span>
      <span class="savingRolls-Line3Right" style="margin-left: 60px">2</span>
      <span class="savingRolls-Line3Right" style="margin-left: 60px">3</span>
      <span class="savingRolls-Line3Right" style="margin-left: 50px">4-5</span>
      <span class="savingRolls-Line3Right" style="margin-left: 50px">6</span>
    </div>

  </div>
  <div class="savingRolls-dataLine" ng-repeat="sr in savingRollList" ng-class-odd="'oddrow'" ng-controller="SavingRollCtrl">
    <span class="savingRolls-sid savingRolls-Data" style="margin-left: 32px">{{sr.sid}}</span>
    <span class="savingRolls-Data" style="margin-left: 72px">{{sr.c1}}</span>
    <span class="savingRolls-Data" style="margin-left: 56px">{{sr.c2}}</span>
    <span class="savingRolls-Data" style="margin-left: 56px">{{sr.c3}}</span>
    <span class="savingRolls-Data" style="margin-left: 60px">{{sr.c4}}</span>
    <span class="savingRolls-Data" style="margin-left: 56px">{{sr.c5}}</span>
    <span class="savingRolls-Data savingRolls-dataAction" style="margin-left: 60px">
      <%= link_to("edit", '#', remote: true, class: '', 'ng-click': "savingRollEditInline({{sr.id}})" ) %> / 
      <%= link_to("delete", '#', remote: true, 'ng-really-message': 'Confirm removal of row', 'ng-really-click': 'srDelete({{sr}})') %>
    </span>
  </div>

  <div class="savingRolls-addForm col-lg-4">
  <%= form_tag srAdd_path, remote: true do %>
    <div class="borderBottom_grey savingRolls-editRow" id="savingRolls-editRow">
        <div class="savingRolls-Input" style="left: 10px;">
          <%= text_field_tag "srAdd[sid]", nil, size: 5, 'ng-model': 'srrow.sid' %>    
        </div>
        
        <div class="savingRolls-Input" style="left: 68px;">
          <%= text_field_tag "srAdd[c1]", nil, size: 1, 'ng-model': 'srrow.c1' %>    
        </div>
        
        <div class="savingRolls-Input" style="left:108px;">
          <%= text_field_tag "srAdd[c2]", nil, size: 1, 'ng-model': 'srrow.c2' %>
        </div>
        
        <div class="savingRolls-Input" style="left:150px;">
          <%= text_field_tag "srAdd[c3]", nil, size: 1, 'ng-model': 'srrow.c3' %>
        </div>
        
        <div class="savingRolls-Input" style="left: 196px;">
          <%= text_field_tag "srAdd[c4]", nil, size: 1, 'ng-model': 'srrow.c4' %>
        </div>
        
        <div class="savingRolls-Input" style="left: 240px;">
          <%= text_field_tag "srAdd[c5]", nil, size: 1, 'ng-model': 'srrow.c5' %>
        </div>
        
        <div class="savingRolls-Input" style="left: 295px;">
          <%= submit_tag "Add", { 'ng-click': 'srAdd(srrow)' } %>
        </div>
    </div>
  <% end %>
    
  </div>

  <div class="clearleft btn-back">
      <button type="button" ng-click="backToTableIndex('savingroll')">Back</button> to Table Index
  </div>
</div>

app/views/admin/_user.html.erb
<% @users.each do |user| %>
  <div class="well well-sm">
    <li>
    <div class="col-lg-4">
      <%= link_to user.uname, "#", id: "uname#{user.id}", remote: true, data: { toggle: 'modal', target: '#edituserModal'} %>
    </div>
    <div class="col-lg-4">
      <span id="email<%= user.id %>"><%= user.email %></span>
    </div>
    <div class="col-lg-4 text-right">
      delete
    </div>
    </li>
  </div>
<% end %>
<!-- Modal -->
<div id="edituserModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<script type="text/javascript">
  $('')
</script>

app/views/admin/_userlist.html.erb
<div ng-controller="adminUserListCtrl">

  <div class="well well-sm" ng-repeat="user in userlist track by user.id" id="wellforUser{{user.id}}">
  <li>
      <div class="col-lg-4">
        <%= link_to "{{user.uname}}", "utility/showEditUser/{{user.id}}", id: "uname{{user.id}}", remote: true %>
      </div>
      <div class="col-lg-4">
        <span id="email{{user.id}}">{{user.email}}</span>
      </div>
      <div class="col-lg-4 text-right">
        <button type="button" ng-really-message="Confirm removal of {{user.uname}}" ng-really-click="removeUser({{user.id}})" >
          <i class="glyphicon glyphicon-trash"></i>
        </button>
      </div>
    </li>
  </div>
</div>